plugins {
    alias libs.plugins.library
    alias libs.plugins.kotlin
    alias libs.plugins.compose.compiler
}

android {
    namespace 'com.ktomek.yamv.koin'
    compileSdk 36
    defaultConfig {
        minSdk 24
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    api project(':yamv-viewmodel')
    implementation project(':core')
    implementation libs.koin.core
    implementation libs.koin.android
    implementation libs.koin.compose
    implementation libs.bundles.compose
}
