pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        mavenLocal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
}
rootProject.name = "yamv"

include ':app'
include ':core'
include ':processor-core'
include ':processor-hilt'
include ':yamv'
include ':yamv-viewmodel'
include ':yamv-hilt'
