package com.ktomek.yamv.processor.fixtures

import com.google.common.truth.Truth.assertThat
import org.junit.jupiter.api.Test
import java.io.File

/**
 * Asserts the contents of `*FeaturesModule.kt` files generated by `:yamv-processor-hilt` for
 * each recognized feature shape. The fixture sources live under `src/main/kotlin/.../fixtures/`;
 * KSP runs them on every build, and this test reads the resulting Kotlin source as text and
 * pattern-matches the binding decision (`@Binds` vs `@Provides … = it.wrap()`).
 */
class GeneratedFeaturesModuleTest {

    @Test
    fun `class-level FlowFeature is bound directly via @Binds`() {
        val module = readModule("binds", "BindsStateFeaturesModule")
        assertBinds(module, paramType = "BindsFlowFeature", returnState = "BindsState")
        assertNotProvidesWithWrap(module, name = "providesBindsFlowFeature")
    }

    @Test
    fun `class-level FlowUnitFeature is bound directly via @Binds`() {
        val module = readModule("binds", "BindsStateFeaturesModule")
        assertBinds(module, paramType = "BindsFlowUnitFeature", returnState = "BindsState")
        assertNotProvidesWithWrap(module, name = "providesBindsFlowUnitFeature")
    }

    @Test
    fun `class-level FunctionTypedFeature is wrapped via @Provides`() {
        val module = readModule("wrap", "WrapStateFeaturesModule")
        assertProvidesWithWrap(
            module,
            name = "providesWrapFunctionTypedFeature",
            paramType = "WrapFunctionTypedFeature",
            returnState = "WrapState",
        )
    }

    @Test
    fun `class-level TypedFeature is wrapped via @Provides`() {
        val module = readModule("wrap", "WrapStateFeaturesModule")
        assertProvidesWithWrap(
            module,
            name = "providesWrapTypedFeatureClass",
            paramType = "WrapTypedFeatureClass",
            returnState = "WrapState",
        )
    }

    @Test
    fun `class-level ActionTypedFeature is wrapped via @Provides`() {
        val module = readModule("wrap", "WrapStateFeaturesModule")
        assertProvidesWithWrap(
            module,
            name = "providesWrapActionTypedFeature",
            paramType = "WrapActionTypedFeature",
            returnState = "WrapState",
        )
    }

    @Test
    fun `class-level TypedUnitFeature is wrapped via @Provides`() {
        val module = readModule("wrap", "WrapStateFeaturesModule")
        assertProvidesWithWrap(
            module,
            name = "providesWrapTypedUnitFeatureClass",
            paramType = "WrapTypedUnitFeatureClass",
            returnState = "WrapState",
        )
    }

    @Test
    fun `property of type Feature is referenced directly without wrap`() {
        val module = readModule("property", "PropertyStateFeaturesModule")
        assertThat(module).contains("providesPropertyAlreadyWrappedFeature")
        assertThat(module).contains(
            "providesPropertyAlreadyWrappedFeature(): Feature<PropertyState> = " +
                "com.ktomek.yamv.processor.fixtures.property.propertyAlreadyWrappedFeature",
        )
        assertThat(module).doesNotContain(
            "propertyAlreadyWrappedFeature.wrap()",
        )
    }

    @Test
    fun `property-level FunctionTypedFeature is wrapped`() {
        assertPropertyWrapped("propertyFunctionTypedFeature")
    }

    @Test
    fun `property-level TypedFeature is wrapped`() {
        assertPropertyWrapped("propertyTypedFeature")
    }

    @Test
    fun `property-level ActionTypedFeature is wrapped`() {
        assertPropertyWrapped("propertyActionTypedFeature")
    }

    @Test
    fun `property-level TypedUnitFeature is wrapped`() {
        assertPropertyWrapped("propertyTypedUnitFeature")
    }

    private fun assertPropertyWrapped(propertyName: String) {
        val module = readModule("property", "PropertyStateFeaturesModule")
        val providerName = "provides" + propertyName.replaceFirstChar { it.uppercaseChar() }
        assertThat(module).contains(providerName)
        assertThat(module).contains(
            "$providerName(): Feature<PropertyState> = " +
                "com.ktomek.yamv.processor.fixtures.property.$propertyName.wrap()",
        )
    }

    private fun assertBinds(module: String, paramType: String, returnState: String) {
        val signature = "binds$paramType(it: $paramType): Feature<$returnState>"
        assertThat(module).contains("@Binds")
        assertThat(module).contains(signature)
    }

    private fun assertProvidesWithWrap(
        module: String,
        name: String,
        paramType: String,
        returnState: String,
    ) {
        val signature =
            "$name(it: $paramType): Feature<$returnState> = it.wrap()"
        assertThat(module).contains(signature)
    }

    private fun assertNotProvidesWithWrap(module: String, name: String) {
        assertThat(module).doesNotContain("$name(it:")
    }

    private fun readModule(packageName: String, moduleName: String): String {
        val path = "build/generated/ksp/debug/kotlin/com/ktomek/yamv/processor/fixtures/" +
            "$packageName/$moduleName.kt"
        val file = File(path)
        check(file.exists()) {
            "Generated module not found at ${file.absolutePath}. Did KSP run? " +
                "Try running `./gradlew :yamv-processor-hilt-fixtures:kspDebugKotlin` first."
        }
        return file.readText()
    }
}
